- README.md
- dtools/push/action.yaml
We use often `tmp-sha` images instead of `github.ref_name` (which is the branch name in most cases). Let's allow to configure it!
> custom destination tag for dtools push

- go/lint/action.yaml
Bumped golangci-lint version (action + binary)
Additionally:
- added additional parameters to golangci-lint
The old version of [golangci-lint action](https://github.com/golangci/golangci-lint-action) ignores the golang version installed by [setup-go action](https://github.com/actions/setup-go) and uses the one installed on the host. As the gha runner was [updated recently](https://github.com/actions/runner-images/commit/54ec59e5eeeec78bdf1424076214017a85313934#diff-fbbd26652e305be8b13c83d79ad91d7105dc03f8ea64a13eeaf95b857118f5aaR218) and the go `1.19.x` is now installed by default on `ubuntu-latest` runner, we had some memory problem with it.
As the problem is quite complex we decided to update both golangci-lint binary and corresponding action.
The updated action was tested on a few of …
> INTERNAL-1 Bumped golangci-lint version

- python/lint/action.yaml
I don't want shitload of
```
reporting/__init__.py already well formatted, good job.
reporting/analytics/__init__.py already well formatted, good job.
reporting/analytics/admin.py already well formatted, good job.
reporting/analytics/apps.py already well formatted, good job.
reporting/analytics/events.py already well formatted, good job.
reporting/analytics/management/commands/__init__.py already well formatted, good job.
reporting/analytics/exceptions.py already well formatted, good job.
```
I know I did the good job..
I just want to know that
```
would reformat reporting/scheduler/test/conftest.py
```
> PPNA-666 less verbose black linter

- changelog/verify/action.yaml
The latest release of python-kacl isn't a great success. Temporarily, we'll lock to the previous one
> lock python-kacl to 0.2.30

- go/lint/action.yaml
Use newer golint that uses gosec who gets rid of
rule G307 which checks when an error is not handled when a file or socket connection is closed
Related issue:
https://github.com/securego/gosec/issues/925
> INT-0 bump golint

- go/lint/.golangci.yml
After golint update, depguards throws a lot errors `depguard XXX is not allowed from list 'Main'`
Untill we find what is going on and fix it we decided to temporarily disable it
> INT-0 disable depguard

- README.md
- godtools/download/action.yaml
- godtools/s3_download/action.yaml
example usage: https://github.com/PiwikPRO/PPMS-Analytics-Reporting/actions/runs/6322622563/job/17168583382#step:7:1
> PPNA-666 Add godtools/s3_download/action

- go/setup/integration/action.yaml
Python 3.12 has no longer `setuptools` [preinstalled](https://docs.python.org/3/whatsnew/3.12.html) which causes the next step to fail
https://github.com/PiwikPRO/Deployment-agent/actions/runs/6669591459/job/18127698177?pr=72
> DEVOPS-6972 python 3.12 setuptools fix

- godtools/setup/action.yaml
Currently, godtools setup action is taking the `latest` release so we're not able to test out new features - without putting CI environments at risk if something goes wrong. 
This PR sets the fixed current version of godtools.
> freeze godtools version to be able to test out new releases

- techdocs/script/config.py
- techdocs/script/nodes.py
- techdocs/script/test_config.py
- techdocs/script/test_copier.py
In current solution such configuration:
```
source: docs/*.md
```
Would cause an error that `Source file `docs/*.md` does not exist` - obviously, this isn't a pointer to a single file but a wildcard suggesting that we're looking for set of files. 
Additional check for "wildcardishness" for `SourceFileMustExist` validator should do the trick. I've added some test cases as a proof.
> Fix handling `source: docs/*.md` pattern

- .github/workflows/push_docs.yaml
Fixes missing branch switch from https://github.com/PiwikPRO/actions/pull/68
> ARCH-256 copier action branch switch

- techdocs/script/cli.py
- techdocs/script/copier.py
- techdocs/script/detectors.py
- techdocs/script/index.py
- techdocs/script/operations.py
- techdocs/script/test_cli_integration.py
- techdocs/script/test_copier.py
- techdocs/script/test_detectors.py
After all those refactors I added an "integration" tests that directly calls `cli.py` with subprocess, to make sure, that everything still glues together correctly.
If you'd like to test that, you need (unfortunately) to setup a local directory for synchronization yourself. If a single "plantuml" file is spotted in the copy rule it should automatically be considered a diagram and converted using docker container.
I used such config for tests, the `--from` is `Promil-docs` repo, `--to` is `Tech-docs` repo:
```json
{
"documents":  [
{
"source": "docs/internal/diagrams/src/azure/systemContext.puml", 
"destination": "diagrams/azure.svg", 
"project": "promil"
}
]
}
```
How it looks:
```sh
$ python cli.py copy --from ~/Projects/promil/Promil-docs --to ~/Projects/promil/Tech-docs --config …
```
> ARCH-275 Aggregation of PlantUML diagrams

- python/lint/action.yaml
Black is changing default rules from time to time, but it breaks builds, so I fixed black version
https://github.com/PiwikPRO/PPMS-Analytics-Reporting/actions/runs/7624315110/job/20962067961 vs https://github.com/PiwikPRO/PPMS-Analytics-Reporting/actions/runs/7693938816/job/20963795926
> Pin black to 23.12.1

- godtools/setup/action.yaml
`0.0.14` wasn't backward compatible which is fixed in `0.0.15` 
Check godtools releases for details
> Update godtools version

- godtools/push/action.yaml
- godtools/setup/action.yaml
If tag is not a semver - just skip the steps instead of failing build.
There is a `sign-only-semver` attribute to bypass that check if necessary.
> Dont fail build if tag is not a valid semver

- .github/workflows/push_docs.yaml
local-dev script silently errored with:
```
python: can't open file '/tmp/actions/techdocs/script/cli.py': [Errno 2] No such file or directory
```
For some reason when `local-dev` tries to git clone actions repo (despite being public) git is throwing `git@github.com: permission denied (publickey)`
This change introduce workaround for this.
PS. There is separate pull request for those silenced errors in `local-dev`.
> Assert actions repository for local-dev script 

- godtools/push/action.yaml
Additionally to tmp images like `tmp-49f6fb9` we will also create tmp image for given branch with some additional sanitization to meet docker tag criteria.
For this branch `feature/ARCH-404-tag-tmp-with-branch` it would be `tmp-feature-arch-404-tag-tmp-with-branch`
Those images will share the retention policy with existing ones.
That approach allows one of our teams to preserve their development habits.
> ARCH-404 tag tmp images by commit AND by branch

- godtools/setup/action.yaml
Small update that removes deprecation warning:
> Node.js 16 actions are deprecated.
> update fetch-gh-release-asset version to 1.1.2

- go/release/action.yaml
the release action
Example usage https://github.com/PiwikPRO/barman/actions/runs/9891857348/job/27323186590
> PET-47 Add possibility to generate sha256 checksum for go binaries in

- techdocs/script/cli.py
- techdocs/script/config.py
- techdocs/script/test_config.py
Example config:
```json
{
"documents": [
{
"source": "docs/*.yaml",
"exclude": ["paths/"],
"destination": "analytics/",
"project": "non-existing"
},
{
"source": "docs/*.yaml",
"exclude": ["paths/"],
"destination": "tag-manager/",
"project": "http-api"
}
]
}
```
Current behavior
```
❯ python cli.py copy --from /tmp/copier --to /tmp/copier/destination --config config.json --index TwojeStareRepo                         
Config file load error: Project `non-existing` is not declared in target's projects.json. Offending config: {'source': 'docs/*.yaml', 'exclude': ['paths/'], 'destination': 'service/', 'project': 'non-existing'}
```
With additional flag
```
❯ python cli.py copy --from /tmp/copier --to /tmp/copier/destination --config config.json --index TwojeStareRepo --skip-invalid-documents …
```
> skip-invalid-documents flag

- go/lint/.golangci.yml
```
WARN [lintersdb] The linter named "megacheck" is deprecated. It has been split into: gosimple, staticcheck, unused. 
WARN The linter 'ifshort' is deprecated (since v1.48.0) due to: The repository of the linter has been deprecated by the owner.  
ERRO [linters_context] ifshort: This linter is fully inactivated: it will not produce any reports. 
exit status 7
exit status 7
```
> DEVOPS-7990 Update deprecated linters

- techdocs/script/conftest.py
- techdocs/script/detectors.py
- techdocs/script/frontmatter.py
- techdocs/script/nodes.py
- techdocs/script/operations.py
- techdocs/script/test_copier.py
- techdocs/script/test_detectors.py
- techdocs/script/test_operations.py
This pr fixes a bug due to specifying `*.txt` with a destination like `/foo` will copy all .txt files from the entire source to foo, flattening the directory structure.
So files like:
```
text.txt
dir/text2.txt
another-dir/and-another/text3.txt
```
improperly becomes 
```
foo/text.txt
foo/text2.txt
foo/text3.txt
```
**Now this case is fixed and will only copy top level `foo/text.txt` according to the pattern.** 
This pr also adds support for glob pattern `**/*` which will now copy recursively directories and files if set. 
So having `**/*.txt`:
```
text.txt
dir/text2.txt
another-dir/and-another/text3.txt
```
Will create such structure:
```
foo/text.txt
foo/dir/text2.txt
foo/another-dir/and-another/text3.txt
```
> ARCH-288 fix wildcard pattern handling (`*.txt` vs `**/*.txt`)

- .github/workflows/push_docs.yaml
- techdocs/script/detectors.py
- techdocs/script/operations.py
This is the first iteration of common validator for openapi specification. It's very simple right now yet it can catch some inconsistencies in specification like parameter mismatch or some leftover spec. 
Check related task comments for some examples.
> Add OpenAPIValidator for catching openapi errors

- godtools/push/action.yaml
As discussed in this [slack thread](https://piwikpro.slack.com/archives/C01C0M9F1KQ/p1739206709185989)  - current semver restriction did cause some confusion.
After discussing with Security SIG we decided to remove this restriction entirely. From now on every git tag will be signed no matter what.
> ARCH-630 remove semver restriction while signing image from git tag

- godtools/push/action.yaml
**Before pushing** an image to registry, if it should be signed we will verify that signing configuration is valid as `cosign` doesn't throw any error if expiration date is exceeded. 
This will be done by new `godtools docker sign-verify` command.
> Validate cert / certChain expiration dates before signing

- cosign/download/action.yaml
- godtools/push/action.yaml
Due to occasional hiccups while downloading cosign and unclear jq error behind it:
- Added retry mechanism for downloading cosign binary
- More clear error reporting 
- Bumped cosign binary to latest version `v2.5.3` 
Test run: https://github.com/PiwikPRO/kong/actions/runs/16565977888 
Controlled failed run: https://github.com/PiwikPRO/kong/actions/runs/16566152871
More details in the related task.
> cosign download retry mechanism
