README.md, python/lint/.isort.cfg, python/lint/action.yaml, python/lint/flake8.ini, python/lint/pyproject.toml
Use example https://github.com/PiwikPRO/MMDBSequentialReader/runs/6856935090?check_suite_focus=true
=> PPNA-4785 Add basic python linters

dtools/push/action.yaml, dtools/setup/action.yaml
[Change from:](https://github.com/PiwikPRO/PPMS-Analytics-Reporting/runs/7354744072?check_suite_focus=true#step:3:16)
```
- name: Push the image to registry
uses: PiwikPRO/actions/dtools/push@master
with:
dtools-token: ${{ secrets.DTOOLS_TOKEN }}
image: "new-hope/reporting"
destination-tag: ${{ steps.get-tag.outputs.tag }}
include-registry: acr --include-registry ecr
```
[to ](https://github.com/PiwikPRO/PPMS-Analytics-Reporting/runs/7354870974?check_suite_focus=true#step:3:21)
```
- name: Push the image to registry
uses: PiwikPRO/actions/dtools/push@master
with:
dtools-token: ${{ secrets.DTOOLS_TOKEN }}
image: "new-hope/reporting"
destination-tag: ${{ steps.get-tag.outputs.tag }}
include-registry: acr, ecr
```
=> PPNA-4907 Make include-registry input works better

go/lint/action.yaml, go/release/action.yaml, go/setup/integration/action.yaml, go/test/action.yaml
=> PPCDEV-15665 go version bump in actions

godtools/login/action.yaml, godtools/push/action.yaml, godtools/setup/action.yaml
Drop-in replacement for dtools.
Usage example: https://github.com/PiwikPRO/PPMS-Organization/actions/runs/3391750556
https://github.com/PiwikPRO/PPMS-Organization/pull/235
=> PPCDEV-15715 initial godtools gha

cosign/download/action.yaml
=> DEVOPS-6135 cosign action

cosign/download/action.yaml
=> INT-1 pin cosing version

go/release/action.yaml
https://github.com/PiwikPRO/barman/actions/runs/4242970468/jobs/7375128998
works as intended
=> DEVOPS-6271 CGO_ENABLED as an input parameter

github-app-token-generator/Dockerfile, github-app-token-generator/LICENSE, github-app-token-generator/README.md, github-app-token-generator/action.yml, github-app-token-generator/generate_jwt.rb, github-app-token-generator/get-installation-access-token.sh
Copy of fork code, removed all unneccesary files
=> DEVOPS-5998 move fork to copy

coverage/covcli.py
=> HOTFIX-1 allow equal coverage

go/release/action.yaml
=> DEVOPS-6273 go/release platform modifiers

go/lint/action.yaml, go/release/action.yaml, go/setup/integration/action.yaml, go/test/action.yaml
Bump go version from 1.19 to 1.20
=> INT-0 bump go version

go/release/action.yaml, go/setup/integration/action.yaml, go/test/action.yaml
see https://github.com/actions/setup-go/issues/326
=> HOTFIX-1 use 1.20.x. for go-version instead of 1.20

godtools/login/action.yaml, godtools/push/action.yaml
Fix invalid list of registries for godtools
=> Fix invalid list of registries for godtools

godtools/push/action.yaml
In response to this [thread](https://piwikpro.slack.com/archives/C9L12C8HX/p1691409441701919).
I've added `tag-latest` flag which is enabled by default for backward compatibility.
=> PPPSYS-42560 Add `tag-latest` flag to docker push godtools action

.github/workflows/push_docs.yaml, README.md, techdocs/action.yaml, techdocs/script/cli.py, techdocs/script/copier.py, techdocs/script/operations.py, techdocs/script/test_operations.py
On pull request creation/changes:
- Adds comment if not present
- Updates comment if they are changes in pushed docs
- Removes comment if changes were removed
=> ARCH-256 comment instead of pr description update 

go/lint/action.yaml, go/test/action.yaml
I think it looks better now, parameterized the packages that are under tests. Without chatgpt i would NEVER construct those sed commands, so thanks OpenAI :D
=> Pet 16 ecosystem

godtools/push/action.yaml
This will allow to customize the branch name for team's needs.
=> ARCH-404 :tada: parametrize develop branch name 

go/release/action.yaml
ability to customize go version in release action
=> INT-1 customize go version

.github/workflows/publish_api_docs.yaml, README.md
More details in related jira issue
=> action for publishing public openapi into developer portal

godtools/push/action.yaml
=> Revert "update godtools push destination-tag input handling"

README.md, python/qa-lint/action.yaml, python/qa-lint/pyproject.toml
Done:
- updated linter rules
- no more poetry in action
=> Pit 595 update qa linter rules

techdocs/script/detectors.py, techdocs/script/operations.py, techdocs/script/test_detectors.py
Check related task for details. Sorry for reformat along the way :innocent:
=> ARCH-572 - rerender openapi specs when referenced files changes

techdocs/script/detectors.py, techdocs/script/operations.py, techdocs/script/test_cli_integration.py, techdocs/script/test_detectors.py, techdocs/script/test_operations.py
=> ARCH-572 support nested openapi references

techdocs/script/detectors.py, techdocs/script/operations.py, techdocs/script/test_detectors.py, techdocs/script/test_operations.py
=> Revert "ARCH-572 support nested openapi references"

techdocs/script/detectors.py, techdocs/script/operations.py, techdocs/script/test_detectors.py, techdocs/script/test_operations.py
=> Reapply "ARCH-572 support nested openapi references" (#136)

go/lint/.golangci.yml, go/lint/action.yaml
test run: https://github.com/PiwikPRO/Promil-status-page-updater/pull/16
=> DEVOPS-9094 golangci-lint upgrade
